menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Tzu-Yu Hsu PhD', title: 'Associate Professor', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', institution_address: 'No. 250, Wuxing St, Xinyi District, Taipei City', email: 'tzuyu.hsu@tmu.edu.tw', office: '12F, TMU Daan campus', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Paul Z. Cheng', title: 'PhD student', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'paul.z.cheng@tmu.edu.tw', image: 'assets/img/Paul1.jpg', url: 'Paul'}
- {name: 'Ko-ping Chou', title: 'Research Assistant', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'koping14916@tmu.edu.tw', image: 'assets/img/ko_ping1.jpg', url: 'ko-ping'}
- {name: 'Antonio Martin', title: 'alumni', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'antonio@tmu.edu.tw', image: 'assets/img/Antonio1.jpg', url: 'Antonio'}
- {name: 'Risa Dwi Ratnasari', title: 'alumni', department: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', email: 'risa.wiratnas@gmail.com', image: 'assets/img/Risa1.jpg', url: 'Risa'}

projects:
- {name: 'Self-relted processes & Brain activity', url: 'projects/Self-relted processes'}
- {name: 'Visual awareness, Consciousness, & Brain activity', url: 'projects/visual_awareness'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Tzuyu Hsu', title: 'Associate Professor', institute: 'Graduate Institute of Mind, Brain and Consciousness', institution: 'Taipei Medical University', institution_address: 'No. 250, Wuxing St, Xinyi District, Taipei City', email: 'tzuyu.hsu@tmu.edu.tw', image: 'assets/img/contact.jpg'}
